- alias: "Turn camera ON while armed"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: arming
  action:
    service: switch.turn_on
    entity_id:
      - switch.camera1_detection


- alias: "Turn camera OFF while disarmed"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
  action:
    service: switch.turn_off
    entity_id:
      - switch.camera1_detection


- alias: "Turn camera OFF if disarmed"
  trigger:
    - platform: state
      entity_id:
        - switch.camera1_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: disarmed
  action:
    service: switch.turn_off
    data_template:
      entity_id: "{{ trigger.entity_id }}"


- alias: "Slow down camera if nothing's detected"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.camera1_no_detection
      to: 'on'
  action:
    service: mqtt.publish
    data_template:
      topic: "watsor/cameras/{{ trigger.to_state.object_id.split('_')[0] }}/command"
      payload: "FPS = 3"
      qos: 1
      retain: true


- alias: "Trigger alarm while armed home"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.camera1_person_detected
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm


- alias: "Trigger alarm while armed home"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: armed_home
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: armed_away
  condition:
    condition: template
    value_template: "{{ is_state('binary_sensor.camera1_person_detected', 'on') }}"
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm


- alias: 'Send notification when alarm triggered and activate strobe lights'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
    - service: script.person_detection_alert
      data_template:
        camera: "camera1"
        when: "{{ as_timestamp(trigger.to_state.last_changed) | timestamp_custom('%Y-%m-%d %H:%M:%S', True) }}"
    - service: switch.turn_on
      entity_id:
        - switch.strobe_lights
    - service: shell_command.play_cctv_warning


- alias: 'Deactivate alarm'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      from: 'triggered'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.strobe_lights
