- name: email
  platform: smtp
  server: !secret mail_server
  port: !secret mail_port
  timeout: 15
  sender: !secret mail_sender
  encryption: tls
  username: !secret mail_username
  password: !secret mail_password
  recipient:
    - !secret mail_recipient_1
  sender_name: !secret name
  debug: false

- name: twilio_call
  platform: twilio_call
  from_number: !secret twilio_from_number
